// Code generated from veraPDF-parser 1.30.2 source; DO NOT EDIT by hand — see glyphnames.go for provenance.

package uacheck

// macRomanEncoding is `TrueTypePredefined.MAC_ROMAN_ENCODING`: 256 glyph names, ".notdef" where the encoding defines none.
var macRomanEncoding = [256]string{
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	"space", "exclam", "quotedbl", "numbersign", "dollar", "percent", "ampersand", "quotesingle",
	"parenleft", "parenright", "asterisk", "plus", "comma", "hyphen", "period", "slash",
	"zero", "one", "two", "three", "four", "five", "six", "seven",
	"eight", "nine", "colon", "semicolon", "less", "equal", "greater", "question",
	"at", "A", "B", "C", "D", "E", "F", "G",
	"H", "I", "J", "K", "L", "M", "N", "O",
	"P", "Q", "R", "S", "T", "U", "V", "W",
	"X", "Y", "Z", "bracketleft", "backslash", "bracketright", "asciicircum", "underscore",
	"grave", "a", "b", "c", "d", "e", "f", "g",
	"h", "i", "j", "k", "l", "m", "n", "o",
	"p", "q", "r", "s", "t", "u", "v", "w",
	"x", "y", "z", "braceleft", "bar", "braceright", "asciitilde", ".notdef",
	"Adieresis", "Aring", "Ccedilla", "Eacute", "Ntilde", "Odieresis", "Udieresis", "aacute",
	"agrave", "acircumflex", "adieresis", "atilde", "aring", "ccedilla", "eacute", "egrave",
	"ecircumflex", "edieresis", "iacute", "igrave", "icircumflex", "idieresis", "ntilde", "oacute",
	"ograve", "ocircumflex", "odieresis", "otilde", "uacute", "ugrave", "ucircumflex", "udieresis",
	"dagger", "degree", "cent", "sterling", "section", "bullet", "paragraph", "germandbls",
	"registered", "copyright", "trademark", "acute", "dieresis", ".notdef", "AE", "Oslash",
	".notdef", "plusminus", ".notdef", ".notdef", "yen", "mu", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", "ordfeminine", "ordmasculine", ".notdef", "ae", "oslash",
	"questiondown", "exclamdown", "logicalnot", ".notdef", "florin", ".notdef", ".notdef", "guillemotleft",
	"guillemotright", "ellipsis", "space", "Agrave", "Atilde", "Otilde", "OE", "oe",
	"endash", "emdash", "quotedblleft", "quotedblright", "quoteleft", "quoteright", "divide", ".notdef",
	"ydieresis", "Ydieresis", "fraction", "currency", "guilsinglleft", "guilsinglright", "fi", "fl",
	"daggerdbl", "periodcentered", "quotesinglbase", "quotedblbase", "perthousand", "Acircumflex", "Ecircumflex", "Aacute",
	"Edieresis", "Egrave", "Iacute", "Icircumflex", "Idieresis", "Igrave", "Oacute", "Ocircumflex",
	".notdef", "Ograve", "Uacute", "Ucircumflex", "Ugrave", "dotlessi", "circumflex", "tilde",
	"macron", "breve", "dotaccent", "ring", "cedilla", "hungarumlaut", "ogonek", "caron",
}

// winAnsiEncoding is `TrueTypePredefined.WIN_ANSI_ENCODING`: 256 glyph names, ".notdef" where the encoding defines none.
var winAnsiEncoding = [256]string{
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	"space", "exclam", "quotedbl", "numbersign", "dollar", "percent", "ampersand", "quotesingle",
	"parenleft", "parenright", "asterisk", "plus", "comma", "hyphen", "period", "slash",
	"zero", "one", "two", "three", "four", "five", "six", "seven",
	"eight", "nine", "colon", "semicolon", "less", "equal", "greater", "question",
	"at", "A", "B", "C", "D", "E", "F", "G",
	"H", "I", "J", "K", "L", "M", "N", "O",
	"P", "Q", "R", "S", "T", "U", "V", "W",
	"X", "Y", "Z", "bracketleft", "backslash", "bracketright", "asciicircum", "underscore",
	"grave", "a", "b", "c", "d", "e", "f", "g",
	"h", "i", "j", "k", "l", "m", "n", "o",
	"p", "q", "r", "s", "t", "u", "v", "w",
	"x", "y", "z", "braceleft", "bar", "braceright", "asciitilde", "bullet",
	"Euro", "bullet", "quotesinglbase", "florin", "quotedblbase", "ellipsis", "dagger", "daggerdbl",
	"circumflex", "perthousand", "Scaron", "guilsinglleft", "OE", "bullet", "Zcaron", "bullet",
	"bullet", "quoteleft", "quoteright", "quotedblleft", "quotedblright", "bullet", "endash", "emdash",
	"tilde", "trademark", "scaron", "guilsinglright", "oe", "bullet", "zcaron", "Ydieresis",
	"space", "exclamdown", "cent", "sterling", "currency", "yen", "brokenbar", "section",
	"dieresis", "copyright", "ordfeminine", "guillemotleft", "logicalnot", "hyphen", "registered", "macron",
	"degree", "plusminus", "twosuperior", "threesuperior", "acute", "mu", "paragraph", "periodcentered",
	"cedilla", "onesuperior", "ordmasculine", "guillemotright", "onequarter", "onehalf", "threequarters", "questiondown",
	"Agrave", "Aacute", "Acircumflex", "Atilde", "Adieresis", "Aring", "AE", "Ccedilla",
	"Egrave", "Eacute", "Ecircumflex", "Edieresis", "Igrave", "Iacute", "Icircumflex", "Idieresis",
	"Eth", "Ntilde", "Ograve", "Oacute", "Ocircumflex", "Otilde", "Odieresis", "multiply",
	"Oslash", "Ugrave", "Uacute", "Ucircumflex", "Udieresis", "Yacute", "Thorn", "germandbls",
	"agrave", "aacute", "acircumflex", "atilde", "adieresis", "aring", "ae", "ccedilla",
	"egrave", "eacute", "ecircumflex", "edieresis", "igrave", "iacute", "icircumflex", "idieresis",
	"eth", "ntilde", "ograve", "oacute", "ocircumflex", "otilde", "odieresis", "divide",
	"oslash", "ugrave", "uacute", "ucircumflex", "udieresis", "yacute", "thorn", "ydieresis",
}

// standardEncoding is `TrueTypePredefined.STANDARD_ENCODING`: 256 glyph names, ".notdef" where the encoding defines none.
var standardEncoding = [256]string{
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	"space", "exclam", "quotedbl", "numbersign", "dollar", "percent", "ampersand", "quoteright",
	"parenleft", "parenright", "asterisk", "plus", "comma", "hyphen", "period", "slash",
	"zero", "one", "two", "three", "four", "five", "six", "seven",
	"eight", "nine", "colon", "semicolon", "less", "equal", "greater", "question",
	"at", "A", "B", "C", "D", "E", "F", "G",
	"H", "I", "J", "K", "L", "M", "N", "O",
	"P", "Q", "R", "S", "T", "U", "V", "W",
	"X", "Y", "Z", "bracketleft", "backslash", "bracketright", "asciicircum", "underscore",
	"quoteleft", "a", "b", "c", "d", "e", "f", "g",
	"h", "i", "j", "k", "l", "m", "n", "o",
	"p", "q", "r", "s", "t", "u", "v", "w",
	"x", "y", "z", "braceleft", "bar", "braceright", "asciitilde", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", "exclamdown", "cent", "sterling", "fraction", "yen", "florin", "section",
	"currency", "quotesingle", "quotedblleft", "guillemotleft", "guilsinglleft", "guilsinglright", "fi", "fl",
	".notdef", "endash", "dagger", "daggerdbl", "periodcentered", ".notdef", "paragraph", "bullet",
	"quotesinglbase", "quotedblbase", "quotedblright", "guillemotright", "ellipsis", "perthousand", ".notdef", "questiondown",
	".notdef", "grave", "acute", "circumflex", "tilde", "macron", "breve", "dotaccent",
	"dieresis", ".notdef", "ring", "cedilla", ".notdef", "hungarumlaut", "ogonek", "caron",
	"emdash", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", "AE", ".notdef", "ordfeminine", ".notdef", ".notdef", ".notdef", ".notdef",
	"Lslash", "Oslash", "OE", "ordmasculine", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", "ae", ".notdef", ".notdef", ".notdef", "dotlessi", ".notdef", ".notdef",
	"lslash", "oslash", "oe", "germandbls", ".notdef", ".notdef", ".notdef", ".notdef",
}

// macExpertEncoding is `TrueTypePredefined.MAC_EXPERT_ENCODING`: 256 glyph names, ".notdef" where the encoding defines none.
var macExpertEncoding = [256]string{
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	"space", "exclamsmall", "Hungarumlautsmall", "centoldstyle", "dollaroldstyle", "dollarsuperior", "ampersandsmall", "Acutesmall",
	"parenleftsuperior", "parenrightsuperior", "twodotenleader", "onedotenleader", "comma", "hyphen", "period", "fraction",
	"zerooldstyle", "oneoldstyle", "twooldstyle", "threeoldstyle", "fouroldstyle", "fiveoldstyle", "sixoldstyle", "sevenoldstyle",
	"eightoldstyle", "nineoldstyle", "colon", "semicolon", ".notdef", "threequartersemdash", ".notdef", "questionsmall",
	".notdef", ".notdef", ".notdef", ".notdef", "Ethsmall", ".notdef", ".notdef", "onequarter",
	"onehalf", "threequarters", "oneeighth", "threeeighths", "fiveeighths", "seveneighths", "onethird", "twothirds",
	".notdef", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", "ff", "fi",
	"fl", "ffi", "ffl", "parenleftinferior", ".notdef", "parenrightinferior", "Circumflexsmall", "hypheninferior",
	"Gravesmall", "Asmall", "Bsmall", "Csmall", "Dsmall", "Esmall", "Fsmall", "Gsmall",
	"Hsmall", "Ismall", "Jsmall", "Ksmall", "Lsmall", "Msmall", "Nsmall", "Osmall",
	"Psmall", "Qsmall", "Rsmall", "Ssmall", "Tsmall", "Usmall", "Vsmall", "Wsmall",
	"Xsmall", "Ysmall", "Zsmall", "colonmonetary", "onefitted", "rupiah", "Tildesmall", ".notdef",
	".notdef", "asuperior", "centsuperior", ".notdef", ".notdef", ".notdef", ".notdef", "Aacutesmall",
	"Agravesmall", "Acircumflexsmall", "Adieresissmall", "Atildesmall", "Aringsmall", "Ccedillasmall", "Eacutesmall", "Egravesmall",
	"Ecircumflexsmall", "Edieresissmall", "Iacutesmall", "Igravesmall", "Icircumflexsmall", "Idieresissmall", "Ntildesmall", "Oacutesmall",
	"Ogravesmall", "Ocircumflexsmall", "Odieresissmall", "Otildesmall", "Uacutesmall", "Ugravesmall", "Ucircumflexsmall", "Udieresissmall",
	".notdef", "eightsuperior", "fourinferior", "threeinferior", "sixinferior", "eightinferior", "seveninferior", "Scaronsmall",
	".notdef", "centinferior", "twoinferior", ".notdef", "Dieresissmall", ".notdef", "Caronsmall", "osuperior",
	"fiveinferior", ".notdef", "commainferior", "periodinferior", "Yacutesmall", ".notdef", "dollarinferior", ".notdef",
	".notdef", "Thornsmall", ".notdef", "nineinferior", "zeroinferior", "Zcaronsmall", "AEsmall", "Oslashsmall",
	"questiondownsmall", "oneinferior", "Lslashsmall", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", "Cedillasmall", ".notdef", ".notdef", ".notdef", ".notdef", ".notdef", "OEsmall",
	"figuredash", "hyphensuperior", ".notdef", ".notdef", ".notdef", ".notdef", "exclamdownsmall", ".notdef",
	"Ydieresissmall", ".notdef", "onesuperior", "twosuperior", "threesuperior", "foursuperior", "fivesuperior", "sixsuperior",
	"sevensuperior", "ninesuperior", "zerosuperior", ".notdef", "esuperior", "rsuperior", "tsuperior", ".notdef",
	".notdef", "isuperior", "ssuperior", "dsuperior", ".notdef", ".notdef", ".notdef", ".notdef",
	".notdef", "lsuperior", "Ogoneksmall", "Brevesmall", "Macronsmall", "bsuperior", "nsuperior", "msuperior",
	"commasuperior", "periodsuperior", "Dotaccentsmall", "Ringsmall", ".notdef", ".notdef", ".notdef", ".notdef",
}

// symbolGlyphNames is `SymbolSet`'s set (189 names): a glyph so named answers " " when the Adobe Glyph List does not hold it.
var symbolGlyphNames = map[string]bool{
	"Alpha": true, "Beta": true, "Chi": true, "Delta": true, "Epsilon": true, "Eta": true, "Euro": true, "Gamma": true,
	"Ifraktur": true, "Iota": true, "Kappa": true, "Lambda": true, "Mu": true, "Nu": true, "Omega": true, "Omicron": true,
	"Phi": true, "Pi": true, "Psi": true, "Rfraktur": true, "Rho": true, "Sigma": true, "Tau": true, "Theta": true,
	"Upsilon": true, "Upsilon1": true, "Xi": true, "Zeta": true, "aleph": true, "alpha": true, "ampersand": true, "angle": true,
	"angleleft": true, "angleright": true, "approxequal": true, "arrowboth": true, "arrowdblboth": true, "arrowdbldown": true, "arrowdblleft": true, "arrowdblright": true,
	"arrowdblup": true, "arrowdown": true, "arrowhorizex": true, "arrowleft": true, "arrowright": true, "arrowup": true, "arrowvertex": true, "asteriskmath": true,
	"bar": true, "beta": true, "braceleft": true, "braceright": true, "bracelefttp": true, "braceleftmid": true, "braceleftbt": true, "bracerighttp": true,
	"bracerightmid": true, "bracerightbt": true, "braceex": true, "bracketleft": true, "bracketright": true, "bracketlefttp": true, "bracketleftex": true, "bracketleftbt": true,
	"bracketrighttp": true, "bracketrightex": true, "bracketrightbt": true, "bullet": true, "carriagereturn": true, "chi": true, "circlemultiply": true, "circleplus": true,
	"club": true, "colon": true, "comma": true, "congruent": true, "copyrightsans": true, "copyrightserif": true, "degree": true, "delta": true,
	"diamond": true, "divide": true, "dotmath": true, "eight": true, "element": true, "ellipsis": true, "emptyset": true, "epsilon": true,
	"equal": true, "equivalence": true, "eta": true, "exclam": true, "existential": true, "five": true, "florin": true, "four": true,
	"fraction": true, "gamma": true, "gradient": true, "greater": true, "greaterequal": true, "heart": true, "infinity": true, "integral": true,
	"integraltp": true, "integralex": true, "integralbt": true, "intersection": true, "iota": true, "kappa": true, "lambda": true, "less": true,
	"lessequal": true, "logicaland": true, "logicalnot": true, "logicalor": true, "lozenge": true, "minus": true, "minute": true, "mu": true,
	"multiply": true, "nine": true, "notelement": true, "notequal": true, "notsubset": true, "nu": true, "numbersign": true, "omega": true,
	"omega1": true, "omicron": true, "one": true, "parenleft": true, "parenright": true, "parenlefttp": true, "parenleftex": true, "parenleftbt": true,
	"parenrighttp": true, "parenrightex": true, "parenrightbt": true, "partialdiff": true, "percent": true, "period": true, "perpendicular": true, "phi": true,
	"phi1": true, "pi": true, "plus": true, "plusminus": true, "product": true, "propersubset": true, "propersuperset": true, "proportional": true,
	"psi": true, "question": true, "radical": true, "radicalex": true, "reflexsubset": true, "reflexsuperset": true, "registersans": true, "registerserif": true,
	"rho": true, "second": true, "semicolon": true, "seven": true, "sigma": true, "sigma1": true, "similar": true, "six": true,
	"slash": true, "space": true, "spade": true, "suchthat": true, "summation": true, "tau": true, "therefore": true, "theta": true,
	"theta1": true, "three": true, "trademarksans": true, "trademarkserif": true, "two": true, "underscore": true, "union": true, "universal": true,
	"upsilon": true, "weierstrass": true, "xi": true, "zero": true, "zeta": true,
}

// zapfDingbatsGlyphNames is `ZapfDingbats`'s set (201 names): a glyph so named answers " " when the Adobe Glyph List does not hold it.
var zapfDingbatsGlyphNames = map[string]bool{
	"a100": true, "a101": true, "a102": true, "a103": true, "a104": true, "a105": true, "a106": true, "a107": true,
	"a108": true, "a109": true, "a10": true, "a110": true, "a111": true, "a112": true, "a117": true, "a118": true,
	"a119": true, "a11": true, "a120": true, "a121": true, "a122": true, "a123": true, "a124": true, "a125": true,
	"a126": true, "a127": true, "a128": true, "a129": true, "a12": true, "a130": true, "a131": true, "a132": true,
	"a133": true, "a134": true, "a135": true, "a136": true, "a137": true, "a138": true, "a139": true, "a13": true,
	"a140": true, "a141": true, "a142": true, "a143": true, "a144": true, "a145": true, "a146": true, "a147": true,
	"a148": true, "a149": true, "a14": true, "a150": true, "a151": true, "a152": true, "a153": true, "a154": true,
	"a155": true, "a156": true, "a157": true, "a158": true, "a159": true, "a15": true, "a160": true, "a161": true,
	"a162": true, "a163": true, "a164": true, "a165": true, "a166": true, "a167": true, "a168": true, "a169": true,
	"a16": true, "a170": true, "a171": true, "a172": true, "a173": true, "a174": true, "a175": true, "a176": true,
	"a177": true, "a178": true, "a179": true, "a17": true, "a180": true, "a181": true, "a182": true, "a183": true,
	"a184": true, "a185": true, "a186": true, "a187": true, "a188": true, "a189": true, "a18": true, "a190": true,
	"a191": true, "a192": true, "a193": true, "a194": true, "a195": true, "a196": true, "a197": true, "a198": true,
	"a199": true, "a19": true, "a1": true, "a200": true, "a201": true, "a202": true, "a203": true, "a204": true,
	"a205": true, "a206": true, "a20": true, "a21": true, "a22": true, "a23": true, "a24": true, "a25": true,
	"a26": true, "a27": true, "a28": true, "a29": true, "a2": true, "a30": true, "a31": true, "a32": true,
	"a33": true, "a34": true, "a35": true, "a36": true, "a37": true, "a38": true, "a39": true, "a3": true,
	"a40": true, "a41": true, "a42": true, "a43": true, "a44": true, "a45": true, "a46": true, "a47": true,
	"a48": true, "a49": true, "a4": true, "a50": true, "a51": true, "a52": true, "a53": true, "a54": true,
	"a55": true, "a56": true, "a57": true, "a58": true, "a59": true, "a5": true, "a60": true, "a61": true,
	"a62": true, "a63": true, "a64": true, "a65": true, "a66": true, "a67": true, "a68": true, "a69": true,
	"a6": true, "a70": true, "a71": true, "a72": true, "a73": true, "a74": true, "a75": true, "a76": true,
	"a77": true, "a78": true, "a79": true, "a7": true, "a81": true, "a82": true, "a83": true, "a84": true,
	"a85": true, "a86": true, "a87": true, "a88": true, "a89": true, "a8": true, "a90": true, "a91": true,
	"a92": true, "a93": true, "a94": true, "a95": true, "a96": true, "a97": true, "a98": true, "a99": true,
	"a9": true,
}
